name: Update

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to clone
        required: false
        default: master
        type: string
      server_instance:
        description: TAP server instance to connect
        required: false
        default: dev
        type: choice
        options:
          - dev
          - prod

jobs:
  update:
    runs-on: self-hosted
    environment: ${{ inputs.server_instance }}
    defaults:
      run:
        shell: powershell
        working-directory: 'C:\tap_node'

    steps:
      - name: Verify tools
        run: |
          $tools = @('nssm', 'git', 'python', 'poetry')
          foreach ($tool in $tools) {
            & $tool --version
          }

      - name: Pull changes
        run: |
          $dir = (Get-Location).Path
          if (-not (git config --global --get-all safe.directory | Where-Object { $_ -eq $dir })) {
            git config --global --add safe.directory $dir
          }
          git reset --hard HEAD
          git checkout "${{ github.event.inputs.branch }}"
          git pull
          poetry config http-basic.tap-pypi '${{ vars.ARTIFACTORY_USERNAME }}' '${{ secrets.ARTIFACTORY_PASSWORD }}'
          Remove-Item -Path .venv -Recurse -Force -ErrorAction SilentlyContinue
          python -m venv .venv
          poetry env use .venv/Scripts/python.exe
          poetry install

      - name: Generate run script
        run: |
          if (-not $env:NODE_TOKEN) {
              Write-Error 'NODE_TOKEN is not set in environment variables'
              exit 1
          }
          if (-not $env:RDP_HOST) {
              Write-Error 'RDP_HOST is not set in environment variables'
              exit 1
          }
          @'
          # autogenerated

          $env:ENVIRONMENT = '${{ vars.ENVIRONMENT || 'dev' }}'

          $env:RMQ_SERVER = '${{ vars.RMQ_SERVER }}'
          $env:RMQ_USER = '${{ vars.RMQ_USER }}'
          $env:RMQ_PASSWORD = '${{ secrets.RMQ_PASSWORD }}'
          $env:RMQ_TCP_PORT = '${{ vars.RMQ_TCP_PORT || 5672 }}'
          $env:RMQ_TCP_PROTOCOL = '${{ vars.RMQ_TCP_PROTOCOL || 'amqp' }}'
          $env:RMQ_VIRTUAL_HOST = '${{ vars.RMQ_VIRTUAL_HOST || 'dev' }}'

          $env:SENTRY_SDK_DSN = '${{ vars.SENTRY_SDK_DSN }}'

          $env:KEYCLOAK_URL = '${{ vars.KEYCLOAK_URL }}'
          $env:KEYCLOAK_REALM = '${{ vars.KEYCLOAK_REALM }}'
          $env:KEYCLOAK_CLIENT_ID_SERVICE = '${{ vars.KEYCLOAK_CLIENT_ID_SERVICE }}'
          $env:KEYCLOAK_CLIENT_SECRET_SERVICE = '${{ secrets.KEYCLOAK_CLIENT_SECRET_SERVICE }}'

          $env:ARTIFACTORY_URL = '${{ vars.ARTIFACTORY_URL || 'https://luxproject.luxoft.com/artifactory' }}'
          $env:ARTIFACTORY_USERNAME = '${{ vars.ARTIFACTORY_USERNAME }}'
          $env:ARTIFACTORY_PASSWORD = '${{ secrets.ARTIFACTORY_PASSWORD }}'

          $env:CONSUL_URL = '${{ vars.CONSUL_URL }}'
          $env:CONSUL_TOKEN = '${{ secrets.CONSUL_TOKEN }}'

          $env:RDP_TARGET_USER = '${{ vars.RDP_TARGET_USER }}'
          $env:RDP_DEFAULT_PASSWORD = '${{ secrets.RDP_DEFAULT_PASSWORD }}'

          poetry run python runner.py -p 9001
          '@ | Set-Content run.ps1 -Encoding UTF8

      - name: Rerun
        run: |
          nssm stop tap_node
          Remove-Item node.log -ErrorAction SilentlyContinue
          nssm start tap_node
